commands = {
    'help': 'what we doing here bruh',
    'reply': 'no puncuation \n keyword -> text  ".reply -the keyword-the response-" \n keyword -> text + img ".reply -the keyword-the response-@imgname \n keyword -> img ".reply -the keyword-@imgname"',
    'add': 'send a image with the message .add nameyourimage this will save the image under gvien name to the server' 
}

jokes = [
    'Slime time!',
    'Diamonds in the deep',
    'Building better than Herobrine',
    'Creepers gonna creep',
    'Enderdragon slayer',
    'No time for crafting',
    'Mining for days',
    'Sunrise on the horizon',
    'Creeper-free zone',
    'Surviving the night',
    'Steve lives!',
    'Skeletons at every turn',
    'Into the End',
    'Skeletons in the closet',
    'Braving the storm',
    'Fighting for survival',
    'The power of Redstone',
    'Trading with the villagers',
    'The perfect mine awaits',
    'Mining for diamonds',
    'The world is your sandbox',
    'The perfect world awaits',
    'The adventure never ends',
    'Playing with fire',
    'Building a better world',
    'The perfect adventure awaits',
    'Lost in the wilderness',
    'Taming the horses',
    'The thrill of the hunt',
    'The power of the beacon',
    'Sailing the seven seas',
    'Mastering the art of mining',
    'Finding your way home',
    'Surviving the jungle',
    'The perfect house awaits',
    'Smooth sailing ahead',
    'Battling the enderdragon',
    'Braving the darkness',
    'Exploring the mineshaft',
    'Navigating the ocean',
    'Feeding the animals',
    'Living like a king',
    'The ultimate Minecraft experience',
    'Building a brighter future',
    'The adventure of a lifetime',
    'Conquering the stronghold',
    'Mining like a boss',
    'The perfect survival world',
    'The power of the minecart',
    'The thrill of the fight',
    'The perfect world in sight',
    'Building a new world',
    'Finding the buried treasure',
    'The ultimate Minecraft journey',
    'Storming the fortress',
    'Mining like a madman',
    'Exploring the unknown depths',
    'The journey never ends',
    'Living off the land like a pro',
    'Building the impossible',
    'The perfect skyblock awaits',
    'The perfect survival experience',
    'Enchanting the impossible',
    'Punching trees for days',
    'Saddle up!',
    'Mushrooms for dinner',
    'Just keep mining',
    'Brewing the perfect potion',
    'Digging deep for treasure',
    'Taming the wolves',
    'Fighting the wither',
    'The world is your block',
    'The Nether awaits',
    'The endless adventure',
    'The sky is not the limit',
    'Zombies at the door',
    'Exploring the unknown',
    'Crafting like a pro',
    'Diamonds in the rough',
    'Surviving the elements',
    'Swimming with the fishes',
    'Watch out for lava!',
    'Emeralds for days',
    'Battling the blaze',
    'Stepping through the portal',
    'Just one more block...',
    'Adventuring with friends',
    'Dodging the ghasts',
    'Beacons in the distance',
    'Mining for glory',
    'So we back in the mine got our pick axe swinging from side to side Side side to side This task a grueling one hope to find some diamonds tonight night night Diamonds tonight Heads up you hear a sound turn around and look up total shock fills your body Oh no its you again I could never forget those eyes eyes eyes Eyes eyes eyes Cause baby tonight the creepers trying to steal all our stuff again Cause baby tonight you grab your pick shovel and bolt again And run run until its done done until the sun comes up in the morn Cause baby tonight the creepers trying to steal all our stuff again Just when you think youre safe overhear some hissing from right behind Right right behind Thats a nice life you have shame its gotta end at this time time time Time time time time Blows up then your health ',
    'Well to be perfectly honest in my humble opinion of course without offending anyone who thinks differently from my point of view but also by looking into this matter in a different perspective and without being condemning of ones views and by trying to make it objective and by considering each and every ones valid opinion I honestly believe that I completely forgot what I was going to say',
    'This offends me as a Muslim vegan transgender hipster NativeAmericanlndoChinese hybrid alien agnosticatheist German engineer who vapes fairtrade organic decaffeinated compressed and hydrated extraprotein soy breast milk on the regular and does Hindi Kama Sutra naked crossfit yoga 8 days a week lm also a nonbinary trigender genderqueer male feminist and identify myself as a pastafarian pansexual genderfluid Apache helicopter dog of mega multi alpha beta gamma delta omega combo god of hyper death whos in a polygamous polyamorous relationship to the chihuahua which helped me cross the border of Mexico because it hates Donald Trump My dog also walks me to the park and doggy styles me if you find that weird youre an ignorant arrogant homophobic genderassuming globaphobic bloodthirsty gunloving cisgender pansexual bestial sexist racist incestuous whiteprevilege misogynistic biased objectified raped privileged NaziCommunist slave owner terrorist lesbian',
    '⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿\n⠀⠀⣶⠀⠀⣀⣤⣶⣤⣉⣿⣿⣤⣀\n⠤⣤⣿⣤⣿⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣀\n⠀⠛⠿⠀⠀⠀⠀⠉⣿⣿⣿⣿⣿⠉⠛⠿⣿⣤\n⠀⠀⠀⠀⠀⠀⠀⠀⠿⣿⣿⣿⠛⠀⠀⠀⣶⠿\n⠀⠀⠀⠀⠀⠀⠀⠀⣀⣿⣿⣿⣿⣤⠀⣿⠿\n⠀⠀⠀⠀⠀⠀⠀⣶⣿⣿⣿⣿⣿⣿⣿⣿\n⠀⠀⠀⠀⠀⠀⠀⠿⣿⣿⣿⣿⣿⠿⠉⠉\n⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⣿⣿⠿\n⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠉\n⠀⠀⠀⠀⠀⠀⠀⠀⣛⣿⣭⣶⣀\n⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⠉⠛⣿\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⠀⠀⣿⣿\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣉⠀⣶⠿\n⠀⠀⠀⠀⠀⠀⠀⠀⣶⣿⠿\n⠀⠀⠀⠀⠀⠀⠀⠛⠿⠛',
    'What the fuck did you just fucking say about me you little bitch Ill have you know I graduated top of my class in the Navy Seals and Ive been involved in numerous secret raids on AlQuaeda and I have over 300 confirmed kills I am trained in gorilla warfare and Im the top sniper in the entire US armed forces You are nothing to me but just another target I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth mark my fucking words You think you can get away with saying that shit to me over the Internet Think again fucker As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm maggot The storm that wipes out the pathetic little thing you call your life Youre fucking dead kid I can be anywhere anytime and I can kill you in over seven hundred ways and thats just with my bare hands Not only am I extensively trained in unarmed combat but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent you little shit If only you could have known what unholy retribution your little clever comment was about to bring down upon you maybe you would have held your fucking tongue But you couldnt you didnt and now youre paying the price you goddamn idiot I will shit fury all over you and you will drown in it Youre fucking dead kiddo ',
    'Terraria underground theme lyrics WOOOOOOOW WOOOOOOOOOOOOOOOOOW WOOOOOOOOOOOOOOOOOW dibit dioot TBTBWOOOOOOOWTBTBT WOOOOOOOOOOOOOOOOOW TBTBWOOOOOOOOOOOOOOOOOWTBBTBT dibit dioodDOOOT doooot wAAAAAAAAAAAAAA Balala booT but but BAP but ba dooooot WAAAAAAAAAAAAAAAAAAAAAAAA dadut doot doot bung Bap bop bap cwhAAAAAAAAAAAAAAAAA dOoaCHA doot Cha t chat cht cht AAAAEDJ DOot chchct doot do DADut bung chthhctbapchbopchbap DUbudu wowowowowowowoWOWOWOWOWOWOWOWOWOWWWwwuwuuwuuwuwuuuuuuuuwuwuw wwwwwwwwwwwwwwwWOWOWOWOOWOWOWOWOWOWOW DABADABAdabdbabdbadbb wowowowowooOWOWOWOWOWOOWOWOWmmmmmmWOWOWOWOOOWm m mm m m m mm m wa wa wa wa wa doot OWOWOOWOWOWOOWOWOO WOOWOWOWOWOOWOWdot WOWOWOWOWOWOWWOWOWOWOWOW DABABABABABABBAbabBAbabbababab mmmWOWOWOWOWOWOOWOWOWOWOWooooooo oo o',
    'Well lets say hypothetically that I sharted my pants First and foremost we must acknowledge that this is not a desirable or socially acceptable situation It is a violation of the basic standards of personal hygiene and cleanliness However we must also consider the possibility that this is not entirely my fault Maybe I ate something that didnt agree with me or maybe I was in a situation where I didnt have access to a restroom Regardless its important to take responsibility for the situation and do what needs to be done to rectify it And the most logical solution would be finding a way to clean up the mess and avoiding similar situations in the future ',
    'my pronouns are heshetheyziesieeyveteyececocyheynequixexieyozenenemnisnixnonyoneonsototheroupehperpheypicpurpyqqeququoireriesaesawsayseseiselfshishoshysieswethaethetheethithis onethonthytretytyrvvaevervivievovohvywyxaexerxetxeyxixiexitxtxyxyexyzyeyyoyreytzzazaezayzeezedzetzeyzhezheyzhisseeeanimalbearcatchairdogelephantfoxgorillameowmonkeywoofidk anymor',
    'I went into the pharmacy to buy a Halls then the girl at the cashier said Good evening can I help you Man who says this Everyone knows that cashier girls just say good eveninggood morninggood afternoon but to me she just said Good evening can I help you naughty shes really into me Then I took a red Halls and said I want a strawberry Halls then she said this one is the cherry one the strawberry one is the pinkest look how naughty bro unbelievable the girl had the audacity to say that the red Halls isnt the strawberry one just to start a conversation with me I decided to see how far she would go so I said ah its all the same so she giggled Bro it wasnt a joke there was no reason for her to laugh she laughed to put me at ease and ask for my Snap Im sure So I looked at her in silence for about 40 seconds to make a link in the flirting because it wasnt fair for her to do everything she asked yeah do you want anything else sir Look at that naughty woman offering herself to me during work hours so I was left with Halls in my hand looking at her she started looking around to see if anyone was looking at her to ask for my Snap she was so euphoric with my presence that was starting to sweat and filling her eyes with water certainly imagining our married future Two minutes after I just held Halls and looked into her eyes I reached into my pocket for my wallet and she said please dont hurt me surely imagining some wild sex for being the alpha male that I am So I took out my wallet smiled took out some money and paid the Halls Then I said Ill be back and a tear rolled down her face Surely she is completely in love with me and crying with happiness',
    'Batman I I I caught uhI caught a little Pokemon',
    'Do you wanna know what Pokemon I caught',
    'What Pokemon did you catch Joker',
    'I caught a Lopunny Batman I caught a Lopunny',
    'Oh No Joker Dont tell me',
    'You already know Batman You know what Im gonna do to that thing',
    'Joker Its an animal Joker you cant',
    'BATMAN THERE IS NO LAWS AGAINST THE POKEMON BATMAN I CAN DO WHATEVER I WANT WITH IT',
    'NO GOD OH GOD NO DONT DO IT',
    'IM GONNA DO IT BATMAN',
    'Nah bros got rizzler Rizzly bear The boy who cried rizz Abraham rizzcoln Adolf Rizzler Rizzy Neutron A degree in quantum rizzics Got a ticket for the polar rizzpress Artirizzal intelligence Barack Rizzbama Need a rizztraining Anakin rizzwalker Rizzard of oz Lord of the rizz Performed a rizzerruction Rizzosaurus Rex From the village hidden in the rizz Offering rizztitution and rizzarations Glenn Rizzmire Rizz Khalifa Martin Luther Rizz Kamala Harizz Rizzy Hendrix Jimi Hendrizz Rizzilicious Rizziliguous Rizziologist Rizzilicious Rizziliguous Rizziologist Rizzillionaire Rizz Ranger Rizzy Henariz Jimi Hendrizz Rizzillcious Rizzillguous Rizziologist Rizzillionaire Rizz Ranger The rizz reaper Leader of the rizzistance Chrizz Brown Wolverizz Head coach of the Memphis Rizzlies Prisoner of rizzkaban Rizzaholic Rizza Parks Rizz Hemsworth Albert Rizzenstein Playing rizzident evil Mike rizzowski Franklin Rizzevelt Rizz Hemsworth Albert Rizzenstein Playing rizzident evil Mike rizzowski Queen Erizzabeth Kyle Rizzenhouse Walt Rizzney Signed the declaration of rizzdependence From the state of Rizzouri Rizz Al Ghul Corona Virizz Rizztafarian Rizzie Smalls Rizz Kelly Rizzil war veteran Rizz and Morty Geralt of Rizzia Alvin and the Rizzmunks Otto von rizzmark The last rizzort Got a ticket for the polar rizzpress Artirizzal intelligence First Rizzponder Member of the nation of Rizzlam Crizztiano Rizzaldo Rizzaldinho The grand rizzard Ghost of rizzmas past',
    'At laundry today 3 mortals attempted to intimidate me Unaware of my divine powers I extended my hand and clicked my fingers Then asked them a simple question Do you know the secrets of Yoga fire They are not sure why this changed their minds but it did'
    'Ricky, you cant have a float plane made out of a bunch of shopping carts',
    'Im not a pessimist Im an optometrist',
    'I am the liquor',
    'I am the cheese I am the best character on the show I am better than both the salami and the bologna combined',
    'Thats the way she goes boys Sometimes she goes sometimes she doesnt cause thats the way she goes',
    'Im not the kind of person to say atodaso but you know what Atodaso I fin atodaso',
    'Sunnyvale is under attack by the Green Bastard',
    'Ive been smokin dope for so long I cant tell if its an asset or a liability anymore',
    'Ive been on food stamps and welfare did anybody help me out No',
    'The way she goes boys The way she goes',
    'I am the liquor Randy The liquors calling the shots now',
    'Let the liquor do the thinking Randy',
    'Thats what I said you cant trust freedom when its not in your hand',
    'Freedom 35 Its a state of mind',
    'Im not a book person Im more of a visual learner',
    'Were not trying to hurt anyone were just trying to make a living',
    'Three things always leave a note never touch my fin percocets and do you have any fin percocets',
    'I am the Green Bastard',
    'You cant buy happiness but you can buy liquor and thats pretty much the same thing',
    'Decent I like it',
    'F off with the cameras buddy',
    'The only thing that comes out of the microwave hot is the plate',
    'Im like a sasquatch Julian Im a big hairy man',
    'Ill never forget you Conky 2000'
    "Youre not just a dick, youre a dick with ears.",
    "The only thing worse than losing is losing to you!",
    "I may not be the best, but I'm definitely not like you.",
    "I'm a genius, I'm a god, I'm Kenny Hotz!",
    "Youre like a little gnat that I have to swat!",
    "Youre like a fart in the wind, you just blow away!",
    "I'm not a wimp, I'm a lover!",
    "Youre like a bad rash, you just won't go away!",
    "I'm not a cheater, I'm an innovator!",
    "Youre a coward and a scumbag!",
    "I'm not scared of you, I'm scared of what you represent!",
    "Youre like a turd that won't flush!",
    "I'm not a quitter, I'm a survivor!",
    "Youre like a broken record, you just keep repeating yourself!",
    "Youre not even a speed bump on the road of life!",
    "I'm not a bad guy, I just do bad things sometimes.",
    "Youre like a mosquito, always buzzing in my ear!",
    "I'm not a loser, I'm just not a winner yet.",
    "Youre like a stain on my soul!",
    "Youre not even a bump in the road, you're a pothole!",
    "I'm not a coward, I'm a strategic retreat-er!",
    "Youre like a fly on the wall, always buzzing around!",
    'Sprinting through the fields',
    'The power of the Nether star',
    'The ultimate Minecraft challenge',
    'The perfect Minecraft adventure',
    'The perfect seed awaits',
    'The ultimate Minecraft world',
    'The power of the beacon awaits',
    'The perfect Minecraft experience',
    'The ultimate Minecraft adventure',
    'The perfect survival challenge',
    'The ultimate Minecraft survival',
    'The perfect Minecraft world awaits',
    'The power of the enderdragon',
    'The ultimate Minecraft journey awaits',
    'The ultimate Minecraft challenge awaits',
    'The perfect Minecraft seed awaits',
    'The ultimate Minecraft experience awaits',
    "Youre not even a pimple on the ass of life!",
    "I'm not crazy, I'm just not you!",
    "Youre like a fart in a crowded elevator, you just stink up the place!",
    "Youre not even a footnote in the history of life!",
    "I'm not a failure, I'm just not succeeding yet.",
    'the end'
]
