commands = {
    'help': 'what we doing here bruh',
    'reply': 'no puncuation \n keyword -> text  ".reply -the keyword-the response-" \n keyword -> text + img ".reply -the keyword-the response-@imgname \n keyword -> img ".reply -the keyword-@imgname"',
    'add': 'send a image with the message .add nameyourimage this will save the image under gvien name to the server' 
}

jokes = [
    'Slime time!',
    'Diamonds in the deep',
    'building better than Herobrine',
    'Creepers gonna creep',
    'Enderdragon slayer',
    'No time for crafting',
    'Mining for days',
    'Sunrise on the horizon',
    'Creeper-free zone',
    'Surviving the night',
    'Steve lives!',
    'Skeletons at every turn',
    'Into the End',
    'Skeletons in the closet',
    'Braving the storm',
    'Fighting for survival',
    'The power of Redstone',
    'Trading with the villagers',
    'The perfect mine awaits',
    'Mining for diamonds',
    'The world is your sandbox',
    'The perfect world awaits',
    'The adventure never ends',
    'Playing with fire',
    'Building a better world',
    'The perfect adventure awaits',
    'Lost in the wilderness',
    'Taming the horses',
    'The thrill of the hunt',
    'The power of the beacon',
    'Sailing the seven seas',
    'Mastering the art of mining',
    'Finding your way home',
    'Surviving the jungle',
    'The perfect house awaits',
    'Smooth sailing ahead',
    'Battling the enderdragon',
    'Braving the darkness',
    'Exploring the mineshaft',
    'Navigating the ocean',
    'Feeding the animals',
    'Living like a king',
    'The ultimate Minecraft experience',
    'Building a brighter future',
    'The adventure of a lifetime',
    'Conquering the stronghold',
    'Mining like a boss',
    'The perfect survival world',
    'The power of the minecart',
    'The thrill of the fight',
    'The perfect world in sight',
    'Building a new world',
    'Finding the buried treasure',
    'The ultimate Minecraft journey',
    'Storming the fortress',
    'Mining like a madman',
    'Exploring the unknown depths',
    'The journey never ends',
    'Living off the land like a pro',
    'Building the impossible',
    'The perfect skyblock awaits',
    'The perfect survival experience',
    'Enchanting the impossible',
    'Punching trees for days',
    'Saddle up!',
    'Mushrooms for dinner',
    'Just keep mining',
    'Brewing the perfect potion',
    'Digging deep for treasure',
    'Taming the wolves',
    'Fighting the wither',
    'The world is your block',
    'The Nether awaits',
    'The endless adventure',
    'The sky is not the limit',
    'Zombies at the door',
    'Exploring the unknown',
    'Crafting like a pro',
    'Diamonds in the rough',
    'Surviving the elements',
    'Swimming with the fishes',
    'Watch out for lava!',
    'Emeralds for days',
    'Battling the blaze',
    'Stepping through the portal',
    'Just one more block...',
    'Adventuring with friends',
    'Dodging the ghasts',
    'Beacons in the distance',
    'Mining for glory',
    'So we back in the mine got our pick axe swinging from side to side Side side to side This task a grueling one hope to find some diamonds tonight night night Diamonds tonight Heads up you hear a sound turn around and look up total shock fills your body Oh no its you again I could never forget those eyes eyes eyes Eyes eyes eyes Cause baby tonight the creepers trying to steal all our stuff again Cause baby tonight you grab your pick shovel and bolt again And run run until its done done until the sun comes up in the morn Cause baby tonight the creepers trying to steal all our stuff again Just when you think youre safe overhear some hissing from right behind Right right behind Thats a nice life you have shame its gotta end at this time time time Time time time time Blows up then your health ',
    'Well to be perfectly honest in my humble opinion of course without offending anyone who thinks differently from my point of view but also by looking into this matter in a different perspective and without being condemning of ones views and by trying to make it objective and by considering each and every ones valid opinion I honestly believe that I completely forgot what I was going to say',
    'This offends me as a Muslim vegan transgender hipster NativeAmericanlndoChinese hybrid alien agnosticatheist German engineer who vapes fairtrade organic decaffeinated compressed and hydrated extraprotein soy breast milk on the regular and does Hindi Kama Sutra naked crossfit yoga 8 days a week lm also a nonbinary trigender genderqueer male feminist and identify myself as a pastafarian pansexual genderfluid Apache helicopter dog of mega multi alpha beta gamma delta omega combo god of hyper death whos in a polygamous polyamorous relationship to the chihuahua which helped me cross the border of Mexico because it hates Donald Trump My dog also walks me to the park and doggy styles me if you find that weird youre an ignorant arrogant homophobic genderassuming globaphobic bloodthirsty gunloving cisgender pansexual bestial sexist racist incestuous whiteprevilege misogynistic biased objectified raped privileged NaziCommunist slave owner terrorist lesbian',
    '⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿\n⠀⠀⣶⠀⠀⣀⣤⣶⣤⣉⣿⣿⣤⣀\n⠤⣤⣿⣤⣿⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣀\n⠀⠛⠿⠀⠀⠀⠀⠉⣿⣿⣿⣿⣿⠉⠛⠿⣿⣤\n⠀⠀⠀⠀⠀⠀⠀⠀⠿⣿⣿⣿⠛⠀⠀⠀⣶⠿\n⠀⠀⠀⠀⠀⠀⠀⠀⣀⣿⣿⣿⣿⣤⠀⣿⠿\n⠀⠀⠀⠀⠀⠀⠀⣶⣿⣿⣿⣿⣿⣿⣿⣿\n⠀⠀⠀⠀⠀⠀⠀⠿⣿⣿⣿⣿⣿⠿⠉⠉\n⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⣿⣿⠿\n⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠉\n⠀⠀⠀⠀⠀⠀⠀⠀⣛⣿⣭⣶⣀\n⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⠉⠛⣿\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⠀⠀⣿⣿\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣉⠀⣶⠿\n⠀⠀⠀⠀⠀⠀⠀⠀⣶⣿⠿\n⠀⠀⠀⠀⠀⠀⠀⠛⠿⠛',
    'What the fuck did you just fucking say about me you little bitch Ill have you know I graduated top of my class in the Navy Seals and Ive been involved in numerous secret raids on AlQuaeda and I have over 300 confirmed kills I am trained in gorilla warfare and Im the top sniper in the entire US armed forces You are nothing to me but just another target I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth mark my fucking words You think you can get away with saying that shit to me over the Internet Think again fucker As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm maggot The storm that wipes out the pathetic little thing you call your life Youre fucking dead kid I can be anywhere anytime and I can kill you in over seven hundred ways and thats just with my bare hands Not only am I extensively trained in unarmed combat but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent you little shit If only you could have known what unholy retribution your little clever comment was about to bring down upon you maybe you would have held your fucking tongue But you couldnt you didnt and now youre paying the price you goddamn idiot I will shit fury all over you and you will drown in it Youre fucking dead kiddo ',
    'Terraria underground theme lyrics WOOOOOOOW WOOOOOOOOOOOOOOOOOW WOOOOOOOOOOOOOOOOOW dibit dioot TBTBWOOOOOOOWTBTBT WOOOOOOOOOOOOOOOOOW TBTBWOOOOOOOOOOOOOOOOOWTBBTBT dibit dioodDOOOT doooot wAAAAAAAAAAAAAA Balala booT but but BAP but ba dooooot WAAAAAAAAAAAAAAAAAAAAAAAA dadut doot doot bung Bap bop bap cwhAAAAAAAAAAAAAAAAA dOoaCHA doot Cha t chat cht cht AAAAEDJ DOot chchct doot do DADut bung chthhctbapchbopchbap DUbudu wowowowowowowoWOWOWOWOWOWOWOWOWOWWWwwuwuuwuuwuwuuuuuuuuwuwuw wwwwwwwwwwwwwwwWOWOWOWOOWOWOWOWOWOWOW DABADABAdabdbabdbadbb wowowowowooOWOWOWOWOWOOWOWOWmmmmmmWOWOWOWOOOWm m mm m m m mm m wa wa wa wa wa doot OWOWOOWOWOWOOWOWOO WOOWOWOWOWOOWOWdot WOWOWOWOWOWOWWOWOWOWOWOW DABABABABABABBAbabBAbabbababab mmmWOWOWOWOWOWOOWOWOWOWOWooooooo oo o',
    'Well lets say hypothetically that I sharted my pants First and foremost we must acknowledge that this is not a desirable or socially acceptable situation It is a violation of the basic standards of personal hygiene and cleanliness However we must also consider the possibility that this is not entirely my fault Maybe I ate something that didnt agree with me or maybe I was in a situation where I didnt have access to a restroom Regardless its important to take responsibility for the situation and do what needs to be done to rectify it And the most logical solution would be finding a way to clean up the mess and avoiding similar situations in the future ',
    'my pronouns are heshetheyziesieeyveteyececocyheynequixexieyozenenemnisnixnonyoneonsototheroupehperpheypicpurpyqqeququoireriesaesawsayseseiselfshishoshysieswethaethetheethithis onethonthytretytyrvvaevervivievovohvywyxaexerxetxeyxixiexitxtxyxyexyzyeyyoyreytzzazaezayzeezedzetzeyzhezheyzhisseeeanimalbearcatchairdogelephantfoxgorillameowmonkeywoofidk anymor',
    'I went into the pharmacy to buy a Halls then the girl at the cashier said Good evening can I help you Man who says this Everyone knows that cashier girls just say good eveninggood morninggood afternoon but to me she just said Good evening can I help you naughty shes really into me Then I took a red Halls and said I want a strawberry Halls then she said this one is the cherry one the strawberry one is the pinkest look how naughty bro unbelievable the girl had the audacity to say that the red Halls isnt the strawberry one just to start a conversation with me I decided to see how far she would go so I said ah its all the same so she giggled Bro it wasnt a joke there was no reason for her to laugh she laughed to put me at ease and ask for my Snap Im sure So I looked at her in silence for about 40 seconds to make a link in the flirting because it wasnt fair for her to do everything she asked yeah do you want anything else sir Look at that naughty woman offering herself to me during work hours so I was left with Halls in my hand looking at her she started looking around to see if anyone was looking at her to ask for my Snap she was so euphoric with my presence that was starting to sweat and filling her eyes with water certainly imagining our married future Two minutes after I just held Halls and looked into her eyes I reached into my pocket for my wallet and she said please dont hurt me surely imagining some wild sex for being the alpha male that I am So I took out my wallet smiled took out some money and paid the Halls Then I said Ill be back and a tear rolled down her face Surely she is completely in love with me and crying with happiness',
    'Batman I I I caught uhI caught a little Pokemon',
    'Do you wanna know what Pokemon I caught',
    'What Pokemon did you catch Joker',
    'I caught a Lopunny Batman I caught a Lopunny',
    'Oh No Joker Dont tell me',
    'You already know Batman You know what Im gonna do to that thing',
    'Joker Its an animal Joker you cant',
    'BATMAN THERE IS NO LAWS AGAINST THE POKEMON BATMAN I CAN DO WHATEVER I WANT WITH IT',
    'NO GOD OH GOD NO DONT DO IT',
    'IM GONNA DO IT BATMAN',
    'Nah bros got rizzler Rizzly bear The boy who cried rizz Abraham rizzcoln Adolf Rizzler Rizzy Neutron A degree in quantum rizzics Got a ticket for the polar rizzpress Artirizzal intelligence Barack Rizzbama Need a rizztraining Anakin rizzwalker Rizzard of oz Lord of the rizz Performed a rizzerruction Rizzosaurus Rex From the village hidden in the rizz Offering rizztitution and rizzarations Glenn Rizzmire Rizz Khalifa Martin Luther Rizz Kamala Harizz Rizzy Hendrix Jimi Hendrizz Rizzilicious Rizziliguous Rizziologist Rizzilicious Rizziliguous Rizziologist Rizzillionaire Rizz Ranger Rizzy Henariz Jimi Hendrizz Rizzillcious Rizzillguous Rizziologist Rizzillionaire Rizz Ranger The rizz reaper Leader of the rizzistance Chrizz Brown Wolverizz Head coach of the Memphis Rizzlies Prisoner of rizzkaban Rizzaholic Rizza Parks Rizz Hemsworth Albert Rizzenstein Playing rizzident evil Mike rizzowski Franklin Rizzevelt Rizz Hemsworth Albert Rizzenstein Playing rizzident evil Mike rizzowski Queen Erizzabeth Kyle Rizzenhouse Walt Rizzney Signed the declaration of rizzdependence From the state of Rizzouri Rizz Al Ghul Corona Virizz Rizztafarian Rizzie Smalls Rizz Kelly Rizzil war veteran Rizz and Morty Geralt of Rizzia Alvin and the Rizzmunks Otto von rizzmark The last rizzort Got a ticket for the polar rizzpress Artirizzal intelligence First Rizzponder Member of the nation of Rizzlam Crizztiano Rizzaldo Rizzaldinho The grand rizzard Ghost of rizzmas past',
    'At laundry today 3 mortals attempted to intimidate me Unaware of my divine powers I extended my hand and clicked my fingers Then asked them a simple question Do you know the secrets of Yoga fire They are not sure why this changed their minds but it did'
    'Ricky, you cant have a float plane made out of a bunch of shopping carts',
    'Im not a pessimist Im an optometrist',
    'I am the liquor',
    'I am the cheese I am the best character on the show I am better than both the salami and the bologna combined',
    'Thats the way she goes boys Sometimes she goes sometimes she doesnt cause thats the way she goes',
    'Im not the kind of person to say atodaso but you know what Atodaso I fin atodaso',
    'Sunnyvale is under attack by the Green Bastard',
    'Ive been smokin dope for so long I cant tell if its an asset or a liability anymore',
    'Ive been on food stamps and welfare did anybody help me out No',
    'The way she goes boys The way she goes',
    'I am the liquor Randy The liquors calling the shots now',
    'Let the liquor do the thinking Randy',
    'Thats what I said you cant trust freedom when its not in your hand',
    'Freedom 35 Its a state of mind',
    'Im not a book person Im more of a visual learner',
    'Were not trying to hurt anyone were just trying to make a living',
    'Three things always leave a note never touch my fin percocets and do you have any fin percocets',
    'I am the Green Bastard',
    'You cant buy happiness but you can buy liquor and thats pretty much the same thing',
    'Decent I like it',
    'F off with the cameras buddy',
    'The only thing that comes out of the microwave hot is the plate',
    'Im like a sasquatch Julian Im a big hairy man',
    'Ill never forget you Conky 2000',
    "Why did the Creeper go to the therapist, explode his feelings.", 
    "How does Steve stay fit, by running blocks every day.", 
    "What did the Enderman say to the ocelot, 'Nice to block you!'",
    "Why did the skeleton go to the party, to find some body.",
    "What do you call a creeper that can sing, a Boombox.",
    "Why did the chicken become a Minecraft architect, to build a better coop.",
    "What did the zombie say to the villager, 'Mind if I chew on your brain for a bit?'",
    "Why did the cow become a Minecraft musician, because it had the moo-sic talent.",
    "What do you call a pig that knows karate, a pork chop.",
    "Why was the redstone lamp so bright, it had a great glow-up.",
    "Why did the enderman bring a ladder to the party, because he heard the food was on the second floor.",
    "What do you call a baby zombie pigman, a pork chop.",
    "Why did the ghast join a choir, because it had a hauntingly beautiful voice.",
    "What did the snow golem say to the other, 'Do you smell carrot?'",
    "Why did the chicken join a band, because it had the drumsticks.",
    "What do you call a creeper with a afro, a 'blast' from the past.",
    "Why did the witch go to school, to improve her spell-ing.", 
    "What do you call a group of rabbits hopping backwards, a receding hareline.",
    "send me the bill, cocksuckers",
    "i got bullets for every one of those motherfuckers",
    "karl marx, fuck karl marx, he's a big fucking faggot pussy",
    "suck my balls, my hairy fuckin' big balls, wrap 'em around your fuckin' mouth",
    "god damn cock breath commie motherfuckers",
    "drop dead motherfucker, you fucking ametuers",
    "hey man, fighting it only makes it worse, you just die like the little motherfucker you are",
    "chew on this, fuckhead",
    "rock and roll, motherfuckers, rock and roll",
    "man i might as well have a bullseye in my ass",
    "welcome to beautiful north korea",
    "god damn shit hole is crawling with kpa",
    "lights out, motherfucker",
    "knock, knock",
    "its my ass on the line",
    "look out while you got your plausible deniability",
    "my objective hasn't changed",
    "marcinko, out",
    "i got two men who arent comin home, and im not lettin them die for nothin because of protocol",
    "fuck no, its a total goatfuck, god damn kpa were waitin for us","my men are dead","this place is gonna light up like chinese new year's","copy that, i'll head for the docks, soon as i sanitize this shithole","what've you got","happy fucking birthday, assholes","looks like the douchebag convention's in town","yeah yeah yeah, sure, whatever you say boss","admiral, the train's loaded, i gotta hitch a ride","better dead than red assholes","fuck they locked the area down","well hello, francis","ready or not baby, here i come","miss me, motherfuckers?","showtime","glad to see me, fuckers?","here's dickey","party time","ah christ, here it comes","if you stop yappin","it's a goat fuck admiral, your intel was bull shit, missiles are goin by land, not sea, these motherfuckers are loading 'em on a train","end of the line, motherfuckers","you shit heels are toast","shoddy fucking commie engineering","hope you fucks can swim","get this you fuckin', fucking retard, you dead piece of shit","trick or treat assholes","happy fourth of july, motherfuckers","back to the u s s fucking r, i hoped i'd never come back to this shit hole","feels like christmas","better head to the objective","fuck","keep lookin' the other way, asshole","what the hell is this place","i fucking hate hedge mazes","you gotta be shittin' me","don't these motherfuckers have somethin' to do?","anybody home?","that's just what i fucking need","shit","you assholes just won't stay outta my way","you're mine, asshole","you assholes look better with the lights off anyway","which one of you cocksuckers ordered the special","BOOO-oh","get a load of this fucking place","this place is a fuckin' funhouse","the soviet fuckin' union can fondle my hairy nuts","brother my day just got a whole lot more fucked up","heh, pencil dick","halle fuckin' lujah","god damn elevator","get the hell outta here, marcinko","evac time","need to get the fuck outta here, now","mmn gotta find a way into this dump","aw, jesus","son of a bitch, that was close","god damn i'm gettin' too old for this shit","which one of you motherfuckers wants to die first","sorry assholes, your quiet day at the office is about to get severely fucked up","need to get inside the dam, turbines'll be on the lower level","don't mind me, assholes","come on, hold your balls, let's go","fan fucking tastic","repeat","it's done","i need to get the fuck outta dodge","where's my ride home","haha job's done, admiral","here comes the boom","jesus, you ass","shit fuck piss god damn","jesus fuckin' christ","god damn it, christ","these motherfuckers, FUUCK","fuck me","jesus, son of a bitch","son of a bitch, jesus","god damn fuckers suck ass","uoghghh fuck shit","uoghghh fuckers","i'm gonna gut you like a fish","i'm gonna stick you like a pig","god damn motherfuckin' bitch","these shit heads aren't gonna wax themselves","this is gettin' me exactly no fuckin' where","guess i better make a move","i'm wastin' time","uncle sam ain't payin' me to sit on my ass","well i'll sleep when i'm dead i need to get movin'","ah jesus christ i could use a fuckin' drink","there's no wickedness for the rested","what the fuck was i doing again, oh yeah, fuckin' shit up","better plant his ass in the ground","time to go ninja on his ass","need to take him out quiet","time to clear the fuck out","time to get the fuck outta dodge","come on, get the ammo, i need to get the fuck outta here, let's go","i gotta bag outta here, i gotta move my ass, ok time to get the fuck outta dodge man","hey fuck face","special delivery, assholes","come on, chew it pencil dick","chew on this, fuckhead","catch it","go fetch","here, this is for you","here, hold this for me you little bitch","here comes the pain","here come the party favors","you're gonna like this, you cocksucker","boom time","eat this, you motherfuckers","thats right, nighty night you sweet piece of shit","sleepy time, you fuckin motherfucker","you're out of a job asshole, you're on your way to fuckin nowhere","come on, fuckface","just fuckin die slow, die like the piece of shit you are","you're mine, fuckstain","your shoe's untied","guess who has shit for brains, huh you little piece of shit","who's sleepy, little fella, huh","don't mind me, i'm just here, i'm just takin care of business","surprise","shh","asswipe","come on, you shitstain, bleed all over the place, you pig","put a cork in it, fuckface","ooh jesus","out of my way, shit","that was out fucking standing","i'll see you numbnut motherfuckers on the other side","what the fuck are you lookin at, huh","arrivederci you motherfuckers, yeah","take a fuckin break, you fuckin jerkoff","can't you take a fucking hint, just stay down","stay down, motherfucker, stay down","rest in peace you cocksucker","adios, motherfuckers","outta my fuckin way, francis","ohh, that was pretty","what are you looking at, motherfucker","that's enough outta you, asshole","nothing personal, cockbreath","let me know what it's like in commie heaven","enjoy the ride, cocksucker","have a nice trip","end of the line, you fuckin cockroach","president reagan sends his regards","merry fuckin' christmas, cocksuckers","eat dirt you pussy motherfucker, you puss nuts, eat dirt, you fuckin cocksuckers","yeah well you eat shit and die, boy, you eat shit and die","yeah well fuck you too","i'm gonna fuck your mother in the ass, and then i'm gonna chop her fucking head off, ok","i'm gonna shove it up your ass","listen you little piece of shit, you asswipe, i'm gonna wipe my ass with your tongue","i'm gonna stick my hand up your ass and rip your fuckin brain out through your asshole","you cockbreath","you're mine, baby, you're mine, you piece of shit","god damn ametuers","you look like a can of smashed asshole","show some testicle, you weenies","fuck you too, asshole","die you fucking shit heel","i'm gonna skullfuck you","yeah, a little capitalism for you, huh, pussy? you fucking shit eating pig","fuck your mother, fuck your father, fuck em in the ass, you cocksucker","you fuckin asshole","you little bitch, you suckass pig","i'm over here, fuckface","i'm over here, you prick","fuckin god damn piece of shit","get dead, fuckbag","you fucking pig farmers","fuckers are out in force","it's a god damn commie fuckin convention","motherfuckers have something to do?","assholes are everywhere","gotta get the drop on them bastards","better take care of those fuckers","fuckin commies keep gettin in my way","motherfuckin place is crawling with commies","need to change clips","i'm running low on ammo","i'm running outta ammo","i need to reload","i gotta reload","the factory in unggi is officially foobar","courtesy of the american taxpayer","well we know some of the missiles already made it out","the intel eggheads say they're heading for the docks, where there's ships waiting to take them onboard. what we don't know, is where the missiles are going","i guess it's time for a little ocean air","you haven't lived until you've crossed north korea on the lid of a god damn train, fucking wind is so cold, it would freeze the balls off a fucking polar bear, i hit the border with russia and it doesn't look like the end of the line","are the soviets taking possession of the missiles? only one way to find out","payton's got his fucking panties in a bunch about insubordination","man i tracked these missiles to their base in soviet russia, now i need to find out just what those fuckin assholes are cookin up there","i need to put an end to this bullshit","after all the billions we dumped into that god damn star wars program, who the hell thought that the fuckin commies would beat us to the punch","hey man, the only thing capable of taking down the defense in time is me","these assholes down there are gonna wish they'd pulled duty at the palace today. a major shitstorm's heading their way","payton wants me to wait for backup. bullshit","as soon as them generators are back online, the sub ships out, and the guidance chip goes with it. if that happens, the soviets can chock up the cold war as a win. and if i make it out alive, that's just gravy"
]
